
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt

    apt-get update
    apt-get install -y unzip xvfb libxi6 libgconf-2-4 xdg-utils lsb-release libxtst6 libnss3 libnspr4
    apt-get install -y libgtk-3-0 libatspi2.0-0 libatk-bridge2.0-0 libasound2 libappindicator3-1 fonts-liberation

    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dpkg -i google-chrome-stable_current_amd64.deb
    sudo apt install --assume-yes --fix-broken

    apt-get upgrade -y

    wget https://chromedriver.storage.googleapis.com/78.0.3904.70/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip

    mv chromedriver /usr/bin/chromedriver
    chmod +x /usr/bin/chromedriver

    google-chrome-stable --version

  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

- script:
    python integration.py
  displayName: 'Selenium'